### GET
GET http://localhost:3333/

### POST
POST http://localhost:3333/
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "passwd": "admin",
    "permission": "admin",
    "address": "Rua das Rosas 255",
    "phone": "(79)9 8844-3885"
}