### Create User
POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Eduardo",
    "email": "edu@email.com"
}

### List All Survery
GET http://localhost:3333/surveys
Content-Type: application/json

### Create Survery
POST http://localhost:3333/surveys
Content-Type: application/json

{
    "title": "Queremos ouvir sua opinião!",
    "description": "De 0 a 10 quanto você recomendaria a RocketSeat"
}

### Create Survey User and send Email
POST http://localhost:3333/sendMail
Content-Type: application/json

{
    "email": "edu@email.com",
    "survey_id": "aec920be-ff51-40c1-b332-29926ed5477b"
}